services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5433:5432
 # adicionar o user e o database (duas variaveis)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 