services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gabriellopes1010
      POSTGRES_PASSWORD: teste1234
      POSTGRES_DB: TodoApplicationDatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080